esphome:
  name: storeroom-airmonitor
  friendly_name: Storeroom Air Monitor
  area: Storeroom

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .internal

uart:
  id: pm25sensor
  rx_pin: D4
  baud_rate: 9600

sensor:
  - platform: pm1006
    uart_id: pm25sensor
    pm_2_5:
      name: "PM2.5"
